### ISSUE TITLE
logical problem of generating traces

### ISSUE THREAD

**Issue by RachelShalom** [farbodtaymouri/GanPredictiveMonitoring#2]
Hi
I will describe the problem with an example of predix_len=4.
prefixes are created by taking prefix: with 1,2,3,4 events and then the next event is event number 5
Generator: creates a trace with len=4
then the last element in the generated trace is taken as y_pred -which is event number 4. and it is compared to y_truth which is the  is event number 5

Why is this comparison logical?

**Comment by farbodtaymouri** [comment]
Hi
Thanks for contacting me. Please take a look at page 9 of the attached paper. It gives you a better perspective on how the fake and real prefixes are created.
Kind regards
    On Wednesday, August 18, 2021, 09:25:01 PM GMT+10, Rachel Shalom ***@***.***> wrote:  
 
 


Hi
I will describe the problem with an example of predix_len=4.
prefixes are created by taking prefix: with 1,2,3,4 events and then the next event is event number 5
Generator: creates a trace with len=4
then the last element in the generated trace is taken as y_pred -which is event number 4. and it is compared to y_truth which is the is event number 5

Why is this comparison logical?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RachelShalom** [comment]
Thanks! I read the paper again and it clicked :)
